name: ci

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: lint
    runs-on: ${{matrix.os}}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        node-version: [14, 16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.4.0
          run_install: |
            - args: [--reporter=silent]

      - name: Lint
        run: pnpm lint
